// This file is automatically generated by build.rs

pub const CAN_BURNER_CANISTER_ID: &'static str = "bkyz2-fmaaa-aaaaa-qaaaq-cai";
pub const CAN_FURNACE_CANISTER_ID: &'static str = "bw4dl-smaaa-aaaaa-qaacq-cai";
pub const CAN_BURN_TOKEN_CANISTER_ID: &'static str = "bd3sg-teaaa-aaaaa-qaaba-cai";
pub const CAN_II_CANISTER_ID: &'static str = "br5f7-7uaaa-aaaaa-qaaca-cai";
pub const CAN_ROOT_KEY: &'static str = "[48, 129, 130, 48, 29, 6, 13, 43, 6, 1, 4, 1, 130, 220, 124, 5, 3, 1, 2, 1, 6, 12, 43, 6, 1, 4, 1, 130, 220, 124, 5, 3, 2, 1, 3, 97, 0, 142, 26, 246, 165, 187, 238, 60, 51, 82, 115, 53, 255, 213, 7, 16, 114, 35, 213, 29, 171, 57, 134, 147, 45, 206, 14, 223, 253, 243, 238, 255, 33, 71, 96, 9, 154, 34, 42, 39, 184, 123, 63, 126, 176, 235, 109, 178, 156, 10, 43, 197, 170, 43, 242, 80, 6, 255, 11, 90, 99, 123, 255, 82, 209, 36, 168, 18, 75, 145, 143, 8, 79, 66, 148, 87, 147, 99, 14, 234, 63, 248, 33, 19, 235, 78, 34, 1, 4, 47, 219, 78, 187, 195, 233, 164, 239]";
pub const CAN_MODE: &'static str = "dev";
pub const CAN_IC_HOST: &'static str = "http://localhost:8080";
