// This file is automatically generated by build.rs

pub const CAN_BURNER_CANISTER_ID: &'static str = "bkyz2-fmaaa-aaaaa-qaaaq-cai";
pub const CAN_FURNACE_CANISTER_ID: &'static str = "bd3sg-teaaa-aaaaa-qaaba-cai";
pub const CAN_BURN_TOKEN_CANISTER_ID: &'static str = "be2us-64aaa-aaaaa-qaabq-cai";
pub const CAN_II_CANISTER_ID: &'static str = "br5f7-7uaaa-aaaaa-qaaca-cai";
pub const CAN_ROOT_KEY: &'static str = "[48, 129, 130, 48, 29, 6, 13, 43, 6, 1, 4, 1, 130, 220, 124, 5, 3, 1, 2, 1, 6, 12, 43, 6, 1, 4, 1, 130, 220, 124, 5, 3, 2, 1, 3, 97, 0, 130, 252, 137, 218, 120, 154, 225, 135, 46, 219, 67, 240, 125, 197, 55, 85, 7, 111, 188, 96, 207, 213, 218, 129, 8, 229, 212, 101, 243, 159, 77, 57, 204, 214, 104, 59, 23, 185, 230, 25, 16, 90, 126, 8, 138, 160, 214, 82, 11, 71, 109, 80, 139, 152, 162, 214, 227, 23, 78, 19, 77, 162, 1, 139, 200, 52, 147, 78, 220, 52, 150, 35, 249, 167, 79, 74, 74, 9, 7, 226, 4, 79, 192, 30, 161, 32, 183, 200, 127, 112, 246, 87, 129, 167, 76, 175]";
pub const CAN_MODE: &'static str = "dev";
pub const CAN_IC_HOST: &'static str = "http://localhost:8080";
