// This file is automatically generated by build.rs

pub const CAN_BURNER_CANISTER_ID: &'static str = "bd3sg-teaaa-aaaaa-qaaba-cai";
pub const CAN_FURNACE_CANISTER_ID: &'static str = "be2us-64aaa-aaaaa-qaabq-cai";
pub const CAN_BURN_TOKEN_CANISTER_ID: &'static str = "br5f7-7uaaa-aaaaa-qaaca-cai";
pub const CAN_TRADING_CANISTER_ID: &'static str = "asrmz-lmaaa-aaaaa-qaaeq-cai";
pub const CAN_TRADING_INVITES_CANISTER_ID: &'static str = "a3shf-5eaaa-aaaaa-qaafa-cai";
pub const CAN_II_CANISTER_ID: &'static str = "bw4dl-smaaa-aaaaa-qaacq-cai";
pub const CAN_ROOT_KEY: &'static str = "[48, 129, 130, 48, 29, 6, 13, 43, 6, 1, 4, 1, 130, 220, 124, 5, 3, 1, 2, 1, 6, 12, 43, 6, 1, 4, 1, 130, 220, 124, 5, 3, 2, 1, 3, 97, 0, 185, 196, 1, 158, 201, 204, 80, 252, 188, 27, 110, 97, 69, 151, 154, 220, 129, 62, 90, 206, 84, 233, 207, 186, 230, 149, 4, 212, 66, 29, 175, 244, 43, 131, 102, 111, 75, 126, 208, 221, 133, 116, 195, 243, 187, 171, 229, 242, 12, 128, 195, 95, 50, 105, 252, 27, 89, 48, 249, 205, 67, 127, 124, 136, 150, 107, 116, 196, 11, 116, 197, 80, 76, 229, 73, 193, 24, 38, 32, 127, 18, 25, 121, 18, 43, 214, 40, 205, 126, 143, 41, 143, 39, 49, 166, 225]";
pub const CAN_MODE: &'static str = "dev";
pub const CAN_IC_HOST: &'static str = "http://localhost:8080";
